TEST_PATTERNS = [
        #("HEMACIAS", r"HEMACIAS\s+(\d+[.,]\d+)\s+(milhões\/mm3)"),
        ("HEMÁCIAS", r"(?:HEMACIAS|HEMÁCIAS)\s+(\d+[.,]\d+)\s+(milhões\/mm3)"),
        ("HEMOGLOBINA", r"HEMOGLOBINA\s+(\d+[.,]\d+)\s+(g\/dL)"),
        #("HEMATOCRITO", r"HEMATOCRITO\s+(\d+[.,]\d+)\s+(\%)"),
        ("HEMATÓCRITO", r"(?:HEMATOCRITO|HEMATÓCRITO)\s+(\d+[.,]\d+)\s+(\%)"),
        ("VCM", r"VCM\s+(\d+[.,]\d+)\s+(fl)"),
        ("HCM", r"HCM\s+(\d+[.,]\d+)\s+(pg)"),
        ("CHCM", r"CHCM\s+(\d+[.,]?\d*)\s*(g/dL|g\/dl)"),
        ("RDW", r"RDW\s+(\d+[.,]\d+)\s+(\%)"),
        #("LEUCOCITOS", r"LEUCOCITOS\s+(\d+[.,]?\d*)"),
        ("LEUCÓCITOS", r"(?:LEUCOCITOS|LEUCÓCITOS)\s+(\d+[.,]?\d*)"),
        #("NEUTROFILOS", r"NEUTROFILOS\s+\d+[.,]?\d*\s+(\d+[.,]?\d*)"),
        ("NEUTRÓFILOS", r"(?:NEUTRÓFILOS|NEUTROFILOS)\s+\d+[.,]?\d*\s+(\d+[.,]?\d*)"),
        #("PROMIELOCITOS", r"PROMIELOCITOS\s+\d+[.,]?\d*\s+(\d+[.,]?\d*)"),
        ("PROMIELÓCITOS", r"(?:PROMIELÓCITOS|PROMIELOCITOS)\s+\d+[.,]?\d*\s+(\d+[.,]?\d*)"),
        ("MIELÓCITOS", r"(?:MIELOCITOS|MIELÓCITOS)\s+\d+[.,]?\d*\s+(\d+[.,]?\d*)"),
        #("MIELOCITOS", r"MIELOCITOS\s+\d+[.,]?\d*\s+(\d+[.,]?\d*)"),
        ("METAMIELÓCITOS", r"(?:METAMIELÓCITOS|METAMIELOCITOS)\s+\d+[.,]?\d*\s+(\d+[.,]?\d*)"),
        #("METAMIELOCITOS", r"METAMIELOCITOS\s+\d+[.,]?\d*\s+(\d+[.,]?\d*)"),
        ("BASTONETES", r"BASTONETES\s+\d+[.,]?\d*\s+(\d+[.,]?\d*)"),
        ("SEGMENTADOS", r"SEGMENTADOS\s+\d+[.,]?\d*\s+(\d+[.,]?\d*)"),
        #("EOSINOFILOS", r"EOSINOFILOS\s+\d+[.,]?\d*\s+(\d+[.,]?\d*)"),
        ("EOSINÓFILOS", r"(?:EOSINÓFILOS|EOSINOFILOS)\s+\d+[.,]?\d*\s+(\d+[.,]?\d*)"),
        #("BASOFILOS", r"BASOFILOS\s+\d+[.,]?\d*\s+(\d+[.,]?\d*)"),
        ("BASÓFILOS", r"(?:BASÓFILOS|BASOFILOS)\s+\d+[.,]?\d*\s+(\d+[.,]?\d*)"),
        ("PLAQUETAS", r"PLAQUETAS\s+(\d+[.,]?\d*)"),
        ("VPM (Volume Plaquetário Médio)", r"VPM \(Volume Plaquetário Médio\)\s+(\d+[.,]\d*)"),
        ("LINFÓCITOS TÍPICOS", r"(?:LINFÓCITOS TÍPICOS|LINFOCITOS TIPICOS)\s+\d+[.,]?\d*\s+(\d+[.,]?\d*)"),
        ("LINFÓCITOS ATÍPICOS", r"(?:LINFÓCITOS ATÍPICOS|LINFOCITOS ATIPICOS)\s+\d+[.,]?\d*\s+(\d+[.,]?\d*)"),
        ("LINFÓCITOS", r"(?:LINFÓCITOS|LINFOCITOS)\s+\d+[.,]?\d*\s+(\d+[.,]?\d*)"),

        #("MONOCITOS", r"MONOCITOS\s+\d+[.,]?\d*\s+(\d+[.,]?\d*)"),
        ("MONÓCITOS", r"(?:MONOCITOS|MONÓCITOS)\s+\d+[.,]?\d*\s+(\d+[.,]?\d*)"),
        ("BLASTOS", r"BLASTOS\s+\d+[.,]?\d*\s+(\d+[.,]?\d*)"),
        ("PLAQUETAS", r"PLAQUETAS\s+(\d+)\s+x\s+"),
        ("VMP", r"VMP\s+(\d+[.,]\d+)\s+(fl)"),
        ("GLICOSE", r"GLICOSE.*?RESULTADO\s*:\s*(\d+)\s*(mg\/dL)"),
        ("FERRITINA", r"FERRITINA.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(nanog/mL)"),
        ("HEMOGLOBINA GLICADA - HbA1c", r"HEMOGLOBINA GLICADA - HbA1c.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(%)"),

        ("GLICEMIA MÉDIA ESTIMADA", r"(?:GLICEMIA MÉDIA ESTIMADA|GLICEMIA MEDIA ESTIMADA)\s*:\s*(\d+[.,]?\d*)\s*(mg/dL)"),
        ("FERRO SÉRICO", r"(?:FERRO SÉRICO|FERRO SERICO).*?RESULTADO\s*:\s*(\d+[.,]\d*)\s*(mcg\/dL)"),

        ("TSH", r"TSH.*?RESULTADO\s*:\s*(\d+[.,]\d+)\s*(µUI\/mL)"),
        ("LH", r"LH.*?RESULTADO\s*:\s*(\d+[.,]\d+)\s*(mUI\/mL)"),
        ("FSH", r"FSH.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(mUI\/mL)"),
        ("1,25-DIHIDROXIVITAMINA D", r"1,25-DIHIDROXIVITAMINA D.*?RESULTADO\s*:\s*(\d+[.,]\d+)\s*(pg\/mL)"),
        ("CREATININA", r"CREATININA.*?RESULTADO\s*[:\-]?\s*(\d+[.,]\d+)\s*(mg\/dL)"),
        ("COLESTEROL TOTAL", r"COLESTEROL TOTAL\s*:\s*(\d+)\s*(mg\/dL)"),
        ("TRIGLICERÍDEOS", r"(?:TRIGLICERÍDEOS|TRIGLICERIDEOS)\s*:\s*(\d+)\s*(mg\/dL)"),
        ("COLESTEROL HDL", r"COLESTEROL HDL\s*:\s*(\d+)\s*(mg\/dL)"),
        ("COLESTEROL LDL", r"COLESTEROL LDL\s*:\s*(\d+)\s*(mg\/dL)"),
        ("COLESTEROL NÃO HDL", r"COLESTEROL NÃO HDL\s*:\s*(\d+)\s*(mg\/dL)"),
        ("UREIA", r"UREIA.*?RESULTADO\s*:\s*(\d+)\s*(mg\/dL)"),
        ("SÓDIO", r"(?:SÓDIO|SODIO).*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(mmol/L)"),
        ("POTÁSSIO", r"(?:POTÁSSIO|POTASSIO).*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(mmol/L)"),
        ("FÓSFORO", r"(?:FÓSFORO|FOSFORO).*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(mg/dL)"),
        ("CÁLCIO", r"(?:CÁLCIO|CALCIO).*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(mg/dL)"),
        ("TRANSAMINASE OXALACÉTICA TGO", r"(?:TRANSAMINASE OXALACÉTICA TGO|TRANSAMINASE OXALACETICA TGO)(?:\s*\(AST\))?.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(U/L)"),
        ("TRANSAMINASE PIRÚVICA TGP", r"(?:TRANSAMINASE PIRÚVICA TGP|TRANSAMINASE PIRUVICA TGP)(?:\s*\(ALT\))?.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(U/L)"),

        ("FOSFATASE ALCALINA", r"FOSFATASE ALCALINA.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(U/L)"),
        ("GAMA GLUTAMIL TRANSFERASE", r"GAMA GLUTAMIL TRANSFERASE.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(U/L)"),
        ("BILIRRUBINA TOTAL", r"BILIRRUBINA TOTAL.*?:\s*(\d+[.,]?\d*)\s*(mg/dL)"),
        ("BILIRRUBINA DIRETA", r"BILIRRUBINA DIRETA.*?:\s*(\d+[.,]?\d*)\s*(mg/dL)"),
        ("BILIRRUBINA INDIRETA", r"BILIRRUBINA INDIRETA.*?:\s*(\d+[.,]?\d*)\s*(mg/dL)"),
        ("ALBUMINA", r"ALBUMINA\s*\(g/dL\)\s*:\s*(\d+[.,]?\d*)"),
        ("ALFA 1", r"ALFA 1\s*\(g/dL\).*?:\s*(\d+[.,]?\d*)"),
        ("ALFA 2", r"ALFA 2\s*\(g/dL\).*?:\s*(\d+[.,]?\d*)"),
        ("BETA 1", r"BETA 1\s*\(g/dL\).*?:\s*(\d+[.,]?\d*)"),
        ("BETA 2", r"BETA 2\s*\(g/dL\).*?:\s*(\d+[.,]?\d*)"),
        ("GAMA", r"GAMA\s*\(g/dL\).*?:\s*(\d+[.,]?\d*)"),
        ("RELAÇÃO A/G", r"RELAÇÃO A/G.*?:\s*(\d+[.,]?\d*)"),
        ("PROTEÍNAS TOTAIS", r"PROTEÍNAS TOTAIS.*?:\s*(\d+[.,]?\d*)\s*(g/dL)"),
        ("T4 LIVRE", r"T4 LIVRE.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(ng/dL)"),
        ("VITAMINA D3 25-HIDROXI", r"VITAMINA D3 25-HIDROXI.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(ng/mL)"),
        ("DENSIDADE", r"DENSIDADE\s+(\d+[.,]?\d*)"),
        ("PROTEÍNA ROTINA DE URINA", r"PROTEÍNA\s+(Positivo|Negativo)"),
        ("PH ROTINA DE URINA", r"PH\s+(\d+[.,]?\d*)"),
        ("GLICOSE ROTINA DE URINA", r"GLICOSE\s+(Positivo|Negativo)"),
        ("CORPOS CETÔNICOS ROTINA DE URINA", r"CORPOS CETÔNICOS\s+(Positivo|Negativo)"),
        ("NITRITOS ROTINA DE URINA", r"NITRITOS\s+(Positivo|Negativo)"),
        ("HEMOGLOBINA ROTINA DE URINA", r"HEMOGLOBINA\s+(Positivo|Negativo)"),
        ("BILIRRUBINAS ROTINA DE URINA", r"BILIRRUBINAS\s+(Positivo|Negativo)"),
        ("UROBILINOGÊNIO ROTINA DE URINA", r"UROBILINOGÊNIO\s+(Normal|Anormal|Ausente|Presente|Traços)"),
        ("LEUCÓCITOS (URINA)", r"Análise dos Elementos Urinários.*?LEUCÓCITOS\s+(\d+[.,]?\d*)"),
        ("LEUCÓCITOS (URINA)", r"ANALISES DOS ELEMENTOS URINARIOS.*?LEUCÓCITOS\s+(\d+[.,]?\d*)"),
        ("HEMÁCIAS (URINA)", r"Análise dos Elementos Urinários.*?HEMÁCIAS\s+(\d+[.,]?\d*)"),
        ("HEMÁCIAS (URINA)", r"ANALISES DOS ELEMENTOS URINARIOS.*?HEMÁCIAS\s+(\d+[.,]?\d*)"),
        ("CILINDROS (URINA)", r"Análise dos Elementos Urinários.*?CILINDROS\s+(Ausentes|Presentes)"),
        ("CILINDROS (URINA)", r"ANALISES DOS ELEMENTOS URINARIOS.*?CILINDROS\s+(Ausentes|Presentes)"),
        ("CRISTAIS (URINA)", r"Análise dos Elementos Urinários.*?CRISTAIS\s+(Ausentes|Presentes)"),
        ("CRISTAIS (URINA)", r"ANALISES DOS ELEMENTOS URINARIOS.*?CRISTAIS\s+(Ausentes|Presentes)"),
        ("BACTÉRIAS (URINA)", r"Análise dos Elementos Urinários.*?BACTÉRIAS\s+(\w+)"),
        ("BACTÉRIAS (URINA)", r"ANALISES DOS ELEMENTOS URINARIOS.*?BACTÉRIAS\s+(\w+)"),
        ("CÉLULAS EPITELIAIS (URINA)", r"Análise dos Elementos Urinários.*?CÉLULAS EPITELIAIS\s+(Presente|Ausente|Raras)(?:\s*\(\+\))?"),
        ("CÉLULAS EPITELIAIS (URINA)", r"ANALISES DOS ELEMENTOS URINARIOS.*?CÉLULAS EPITELIAIS\s+(Presente|Ausente|Raras)(?:\s*\(\+\))?"),
        ("OUTROS ELEMENTOS (URINA)", r"OUTROS ELEMENTOS(.*?)(?=Observa|Obs|Nota)"),
        ("PARATORMÔNIO", r"(?:PARATORMÔNIO|PARATORMONIO).*?RESULTADO\s*:?\s*(\d+[.,]?\d*)\s*(pg/mL)"),
        ("PSA LIVRE", r"PSA LIVRE\s*:\s*(\d+[.,]?\d*)\s*(ng/mL)"),
        ("PSA TOTAL", r"PSA TOTAL\s*:\s*(\d+[.,]?\d*)\s*(ng/mL)"),
        ("RELAÇÃO PSA LIVRE/PSA TOTAL", r"RELAÇÃO PSA LIVRE/PSA TOTAL\s*:\s*(\d+[.,]?\d*)\s*(%)"),
        ("MAGNÉSIO", r"(?:MAGNÉSIO|MAGNESIO).*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(mg/dL)"),
        ("pH (GASOMETRIA VENOSA)", r"GASOMETRIA VENOSA.*?pH.*?:\s*([+-]?\d+[.,]?\d*)"),
        ("PCO2 (GASOMETRIA VENOSA)", r"GASOMETRIA VENOSA.*?PCO2.*?:\s*([+-]?\d+[.,]?\d*)\s*(mmHg)"),
        ("PO2 (GASOMETRIA VENOSA)", r"GASOMETRIA VENOSA.*?PO2.*?:\s*([+-]?\d+[.,]?\d*)\s*(mmHg)"),
        ("HCO3 (GASOMETRIA VENOSA)", r"GASOMETRIA VENOSA.*?HCO3.*?:\s*([+-]?\d+[.,]?\d*)\s*(mmol/L)"),
        ("O2 SATURAÇÃO (GASOMETRIA VENOSA)", r"GASOMETRIA VENOSA.*?O2 SATURAÇÃO.*?:\s*([+-]?\d+[.,]?\d*)\s*(%)"),
        ("B.E. (GASOMETRIA VENOSA)", r"GASOMETRIA VENOSA.*?B\.E\..*?:\s*([+-]?\d+[.,]?\d*)\s*(mmol/L)"),
        ("ANTICORPOS ANTI-TRANSGLUTAMINASE TECIDUAL - IgA", r"ANTICORPOS ANTI-TRANSGLUTAMINASE TECIDUAL - IgA.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(U/mL)"),
        ("SOMATOMEDINA - IGF-1", r"SOMATOMEDINA - IGF-1.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(ng/mL)"),
        ("CARIÓTIPO NÚMERO DE CÉLULAS ANALISADAS", r"NÚMERO DE CÉLULAS ANALISADAS\s*:\s*(\d+)"),
        ("CARIÓTIPO RESOLUÇÃO", r"RESOLUÇÃO\s*:\s*(\d+)\s*BANDAS"),
        ("CARIÓTIPO RESOLUÇÃO", r"RESOLUÇÃO\s*:\s*(\d+)\s*"),
        ("CARIÓTIPO RESULTADO", r"CARIÓTIPO\s*:\s*([0-9]{2},[XY]{2})"),
        ("IMUNOGLOBULINAS IgA", r"IMUNOGLOBULINAS IgA.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(mg/dL)"),
        ("VHS 1ª HORA", r"VHS 1ª HORA.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(mm/1h)"),
        ("PROTROMBINA (PACIENTE)", r"PROTROMBINA \(PACIENTE\).*?:\s*(\d+[.,]?\d*)\s*(segundos)"),
        ("ATIVIDADE DE PROTROMBINA", r"ATIVIDADE DE PROTROMBINA\s*:\s*(\d+[.,]?\d*)\s*(%)"),
        ("PROTROMBINA (RELAÇÃO PACIENTE/PADRÃO)", r"PROTROMBINA \(RELAÇÃO PACIENTE/PADRÃO\)\s*:\s*(\d+[.,]?\d*)"),
        ("RELAÇÃO PACIENTE/CONTROLE", r"RELAÇÃO PACIENTE/CONTROLE\s*:\s*(\d+[.,]?\d*)"),
        ("SISTEMA ABO", r"SISTEMA ABO.*?:\s*([A|B|AB|O]{1,2})"),
        ("FATOR RH", r"FATOR RH.*?:\s*(POSITIVO|NEGATIVO)"),
        ("HCG - GONADOTROFINA CORIONICA", r"HCG - GONADOTROFINA CORIONICA.*?RESULTADO\s*:\s*([<>\=]?\s*\d+[.,]?\d*)\s*(mUI/mL)"),
        ("CARIÓTIPO RESULTADO", r"CARIÓTIPO\s*:\s*([0-9]{2},[^\s]+)"),
        ("HOMA IR", r"HOMA IR\s*(\d+[.,]?\d*)"),
        ("HOMA BETA", r"HOMA BETA\s*(\d+[.,]?\d*)"),
        ("ÁCIDO ÚRICO", r"ÁCIDO ÚRICO.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(mg/dL)"),
        ("CEA/ANTIGENO CARCINOEMBRIOGENICO", r"CEA/ANTIGENO CARCINOEMBRIOGENICO.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(ng/mL)"),
        ("VITAMINA B12", r"VITAMINA B12.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(pg/mL)"),
        ("ÁCIDO FÓLICO", r"ÁCIDO FÓLICO.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(ng/mL)"),
        ("INSULINA BASAL", r"INSULINA BASAL.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(mU/mL)"),
        ("HOMOCISTEÍNA", r"HOMOCISTEÍNA.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(µmol/L)"),
        ("CAXUMBA IgG", r"CAXUMBA IgG.*?RESULTADO\s*:\s*([<>\=]?\s*\d+[.,]?\d*)\s*(UA/mL)"),
        ("TESTOSTERONA TOTAL", r"TESTOSTERONA TOTAL.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(ng/dL)"),
        #("ZINCO SERICO", r"ZINCO SERICO.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(ug/dL)"),
        #("ZINCO SÉRICO", r"ZINCO SÉRICO.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(ug/dL)"),
        ("CÁDMIO", r"CÁDMIO.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(mcg/L)"),
        ("CÁDMIO", r"CADMIO.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(mcg/L)"),
        ("ALUMÍNIO", r"ALUMÍNIO.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(mcg/L)"),
        ("MERCÚRIO", r"Mercúrio.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(mcg/dL)"),
        ("MERCÚRIO", r"Mercurio.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(mcg/dL)"),
        ("MANGANÊS", r"MANGANÊS.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(µg/L)"),
        ("MANGANÊS", r"MANGANES.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(µg/L)"),
        ("ARSÊNICO", r"ARSÊNICO.*?RESULTADO\s*:\s*(INFERIOR A\s*\d+[.,]?\d*)\s*(mcg/L)"),
        ("ARSÊNICO", r"ARSENICO.*?RESULTADO\s*:\s*(INFERIOR A\s*\d+[.,]?\d*)\s*(mcg/L)"),
        ("CROMO", r"CROMO.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(µg/L)"),
        ("COBALTO", r"COBALTO.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(µg/L)"),
        ("NÍQUEL", r"(?:NÍQUEL|NIQUEL).*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(mcg/L)"),
        ("N-TELOPEPTÍDEO NTX RESULTADO", r"N-TELOPEPTÍDEO.*?RESULTADO.*?:\s*(\d+[.,]?\d*)\s*(nmol ECO/mM creatinina)"),
        ("N-TELOPEPTÍDEO NTX CONCENTRAÇÃO", r"CONCENTRAÇÃO\s*:\s*(\d+[.,]?\d*)\s*(nmol ECO/L)"),
        ("SOROTIPO 4", r"SOROTIPO\s*4\s*:\s*(Inferior a\s*\d+[.,]?\d*|\d+[.,]?\d*)\s*(microgramas/mL)"),
        ("SOROTIPO 6B", r"SOROTIPO\s*6B\s*:\s*(Inferior a\s*\d+[.,]?\d*|\d+[.,]?\d*)\s*(microgramas/mL)"),
        ("SOROTIPO 9V", r"SOROTIPO\s*9V\s*:\s*(Inferior a\s*\d+[.,]?\d*|\d+[.,]?\d*)\s*(microgramas/mL)"),
        ("SOROTIPO 14", r"SOROTIPO\s*14\s*:\s*(Inferior a\s*\d+[.,]?\d*|\d+[.,]?\d*)\s*(microgramas/mL)"),
        ("SOROTIPO 18C", r"SOROTIPO\s*18C\s*:\s*(Inferior a\s*\d+[.,]?\d*|\d+[.,]?\d*)\s*(microgramas/mL)"),
        ("SOROTIPO 19F", r"SOROTIPO\s*19F\s*:\s*(Inferior a\s*\d+[.,]?\d*|\d+[.,]?\d*)\s*(microgramas/mL)"),
        ("SOROTIPO 23F", r"SOROTIPO\s*23F\s*:\s*(Inferior a\s*\d+[.,]?\d*|\d+[.,]?\d*)\s*(microgramas/mL)",),
        ("IgE MÚLTIPLO PARA PÓ DE CASA", r"IgE MÚLTIPLO PARA PÓ DE CASA \(HX2\).*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(kU/L)"),
        ("IgE MÚLTIPLO PARA EPITÉLIOS E PROTEÍNAS ANIMAIS", r"IgE MÚLTIPLO PARA EPITÉLIOS E PROTEÍNAS ANIMAIS \(EX2\).*?RESULTADO\s*:\s*([<>\=]?\s*\d+[.,]?\d*)\s*(kU/L)"),
        ("IgE MÚLTIPLO PARA ALIMENTOS", r"IgE MÚLTIPLO PARA ALIMENTOS \(FX5\).*?RESULTADO\s*:\s*([<>\=]?\s*\d+[.,]?\d*)\s*(kU/L)"),
        ("IMUNOGLOBULINAS IgE TOTAL", r"IMUNOGLOBULINAS IgE TOTAL.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(UI/mL)"),
        ("CA 125", r"CA 125.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(U/mL)"),
        ("ESTRADIOL", r"ESTRADIOL.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(pg/mL)"),
        ("CPK - CREATINA FOSFOQUINASE", r"CPK - CREATINA FOSFOQUINASE.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(U/L)"),
        ("TESTOSTERONA LIVRE", r"TESTOSTERONA LIVRE.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(pg/mL)"),
        ("ANTICORPOS ANTI CITOMEGALOVÍRUS - IgG",r"ANTICORPOS\s+ANTI\s+CITOMEGALOV[IÍ]RUS\s*-\s*IgG.*?RESULTADO\s*:\s*(?:AMOSTRA\s+)?([<>]?\s*\d+[.,]?\d*)\s*(U/[A-Za-z]+)"),
    ("CITOMEGALOVÍRUS IgM",
     r"CITOMEGALOV[IÍ]RUS\s+IgM.*?RESULTADO\s*:\s*(?:AMOSTRA\s+)?(N[ÃA]O\s+REAGENTE|REAGENTE|INDETERMINADO|<\s*\d+[.,]?\d*)"),
    ("ANTICORPOS TOTAIS ANTI-HBV CORE (HBC)",
     r"ANTICORPOS\s+TOTAIS\s+ANTI-?HBV\s+CORE.*?RESULTADO\s*:\s*(N[ÃA]O\s+REAGENTE|REAGENTE|INDETERMINADO|<\s*\d+[.,]?\d*)"),
    ("CAXUMBA IgG",
     r"CAXUMBA\s+IgG.*?RESULTADO\s*:\s*([<>]?\s*\d+[.,]?\d*)\s*(UA/mL)"),
    ("ANTICORPOS ANTI-TREPONEMA PALLIDUM",
     r"ANTICORPOS\s+ANTI-?TREPONEMA\s+PALLIDUM.*?RESULTADO\s*:\s*(N[ÃA]O\s+REAGENTE|REAGENTE|INDETERMINADO)"),
    ("ANTICORPOS ANTI-TRANSGLUTAMINASE TECIDUAL - IgA",
     r"ANTICORPOS\s+ANTI-TRANSGLUTAMINASE\s+TECIDUAL\s*-\s*IgA.*?RESULTADO\s*:\s*([<>]?\s*\d+[.,]?\d*)\s*(U/mL)"),
    ("ANTICORPOS ANTI-HCV",
     r"ANTICORPOS\s+ANTI-?HCV.*?RESULTADO\s*:\s*(N[ÃA]O\s+REAGENTE|REAGENTE|INDETERMINADO|<\s*\d+[.,]?\d*)"),
    ("ANTICORPOS ANTI-HBS",
     r"ANTICORPOS\s+ANTI-?HBS.*?RESULTADO\s*:\s*(N[ÃA]O\s+REAGENTE|REAGENTE|INDETERMINADO|<\s*\d+[.,]?\d*)"),
    ("ANTÍGENO DE SUPERFÍCIE DO HBV (HBsAg)",
     r"HBsAg.*?RESULTADO\s*:\s*(N[ÃA]O\s+REAGENTE|REAGENTE|INDETERMINADO|<\s*\d+[.,]?\d*)"),
    ("SÍFILIS - FTA-ABS IgG",
     r"S[ÍI]FILIS\s*-\s*FTA-ABS\s+IgG.*?RESULTADO\s*:\s*(N[ÃA]O\s+REAGENTE|REAGENTE|INDETERMINADO)"),

    # --- Exames bioquímicos / hormonais (todos numéricos) -------------
   # ("ALBUMINA",
    # r"ALBUMINA.*?RESULTADO\s*:\s*([<>]?\s*\d+[.,]?\d*)\s*([^\s]+)"),
    ("ALUMÍNIO",
     r"ALUM[IÍ]NIO.*?RESULTADO\s*:\s*([<>]?\s*\d+[.,]?\d*)\s*(mcg/L)"),
    ("AMILASE",
     r"AMILASE.*?RESULTADO\s*:\s*([<>]?\s*\d+[.,]?\d*)\s*(U/L)"),
    ("ANDROSTANEDIOL GLUCURONIDE \\[3 ALFA DIOL\\]",
     r"ANDROSTANEDIOL.*?RESULTADO\s*:\s*([<>]?\s*\d+[.,]?\d*)\s*(ng/mL)"),
    ("ANTI-TPO ( ANTICORPO ANTIPEROXIDASE )",
     r"ANTI-?TPO.*?RESULTADO\s*:\s*([<>]?\s*\d+[.,]?\d*)\s*(UI/mL)"),
    ("ANTICORPOS ANTI MICROSSOMAL",
     r"ANTICORPOS\s+ANTI\s+MICROSSOMAL.*?RESULTADO\s*:\s*([<>]?\s*\d+[.,]?\d*)\s*(UI/mL)"),
    ("ANTICORPOS ANTI TIREOGLOBULINA",
     r"ANTICORPOS\s+ANTI\s+TIREOGLOBULINA.*?RESULTADO\s*:\s*([<>]?\s*\d+[.,]?\d*)\s*(UI/mL)"),
    ("APOLIPOPROTEINA A1",
     r"APOLIPOPROTEINA\s+A1.*?RESULTADO\s*:\s*([<>]?\s*\d+[.,]?\d*)\s*(mg/dL)"),
    ("APOLIPOPROTEINA B",
     r"APOLIPOPROTEINA\s+B.*?RESULTADO\s*:\s*([<>]?\s*\d+[.,]?\d*)\s*(mg/dL)"),
    ("AMILASE",
     r"AMILASE.*?RESULTADO\s*:\s*([<>]?\s*\d+[.,]?\d*)\s*(U/L)"),
    ("AMILASE URINÁRIA",
     r"AMILASE\s+URIN[AÁ]RIA.*?RESULTADO\s*:\s*([<>]?\s*\d+[.,]?\d*)\s*(U/L)"),
    ("APTT / TTPA",
     r"(?:APTT|TTPA).*?RESULTADO\s*:\s*([<>]?\s*\d+[.,]?\d*)\s*(s|segundos)"),
    # r"B[ÍI]LIRRUBINA\s+TOTAL.*?(?:RESULTADO\s*:\s*|[:.]{1,3}\s*)([<>]?\s*\d+[.,]?\d*)\s*(mg/dL)"
#PAT_BILIRRUBINA_DIRETA  = r"B[ÍI]LIRRUBINA\s+DIRETA.*?(?:RESULTADO\s*:\s*|[:.]{1,3}\s*)([<>]?\s*\d+[.,]?\d*)\s*(mg/dL)"
#PAT_BILIRRUBINA_INDIRETA= r"B[ÍI]LIRRUBINA\s+INDIRETA.*?(?:RESULTADO\s*:\s*|[:.]{1,3}\s*)([<>]?\s*\d+[.,]?\d*)\s*(mg/dL)"

    ("CÁLCIO IONIZADO",
     r"C[ÁA]LCIO\s+IONIZADO.*?RESULTADO\s*:\s*([<>]?\s*\d+[.,]?\d*)\s*(mg/dL)"),
    ("CÁLCIO URINÁRIO",
     r"C[ÁA]LCIO\s+URIN[ÁA]RIO.*?RESULTADO\s*:\s*([<>]?\s*\d+[.,]?\d*)\s*(mg/24h)"),
    ("CORTISOL \\(08 HORAS\\)",
     r"CORTISOL\s+\\(08\s+HORAS\\).*?RESULTADO\s*:\s*([<>]?\s*\d+[.,]?\d*)\s*(µ?g/dL)"),
    ("CORTISOL SALIVAR \\(08 HORAS\\)",
     r"CORTISOL\s+SALIVAR\s+\\(08\s+HORAS\\).*?RESULTADO\s*:\s*([<>]?\s*\d+[.,]?\d*)\s*(ng/mL)"),
    ("CORTISOL SALIVAR \\(16 HORAS\\)",
     r"CORTISOL\s+SALIVAR\s+\\(16\s+HORAS\\).*?RESULTADO\s*:\s*([<>]?\s*\d+[.,]?\d*)\s*(ng/mL)"),
    ("CORTISOL SALIVAR \\(22 HORAS\\)",
     r"CORTISOL\s+SALIVAR\s+\\(22\s+HORAS\\).*?RESULTADO\s*:\s*([<>]?\s*\d+[.,]?\d*)\s*(ng/mL)"),
    ("CPK - CREATINA FOSFOQUINASE",
     r"CPK\s*-?\s*CREATINA\s+FOSFOQUINASE.*?RESULTADO\s*:\s*([<>]?\s*\d+[.,]?\d*)\s*(U/L)"),
    ("ESTRADIOL",
     r"ESTRADIOL.*?RESULTADO\s*:\s*([<>]?\s*\d+[.,]?\d*)\s*(pg/mL)"),
    ("FOSFATASE ÁCIDA PROSTÁTICA",
     r"FOSFATASE\s+ÁCIDA\s+PROST[ÁA]TICA.*?RESULTADO\s*:\s*([<>]?\s*\d+[.,]?\d*)\s*(U/L)"),
    ("FSH",
     r"FSH.*?RESULTADO\s*:\s*([<>]?\s*\d+[.,]?\d*)\s*(mUI/mL)"),
    ("INSULINA BASAL",
     r"INSULINA\s+BASAL.*?RESULTADO\s*:\s*([<>]?\s*\d+[.,]?\d*)\s*(mU/mL)"),
    ("LH - HORMÔNIO LUTEINIZANTE",
     r"LH.*?RESULTADO\s*:\s*([<>]?\s*\d+[.,]?\d*)\s*(mUI/mL)"),
    ("LIPASE",
     r"LIPASE.*?RESULTADO\s*:\s*([<>]?\s*\d+[.,]?\d*)\s*(U/L)"),
    ("MAGNÉSIO",
     r"MAGN[ÉE]SIO.*?RESULTADO\s*:\s*([<>]?\s*\d+[.,]?\d*)\s*(mg/dL)"),
    ("MANGANÊS",
     r"MANGAN[ÊE]S.*?RESULTADO\s*:\s*([<>]?\s*\d+[.,]?\d*)\s*(µ?g/L)"),
    ("MERCÚRIO",
     r"MERC[ÚU]RIO.*?RESULTADO\s*:\s*([<>]?\s*\d+[.,]?\d*)\s*(mcg/dL)"),
    ("PO2 \\(GASOMETRIA VENOSA\\)",
     r"GASOMETRIA\s+VENOSA.*?PO2.*?[:|\\s]\\s*([+-]?\\d+[.,]?\\d*)\\s*(mmHg)"),
    ("PCO2 \\(GASOMETRIA VENOSA\\)",
     r"GASOMETRIA\s+VENOSA.*?PCO2.*?[:|\\s]\\s*([+-]?\\d+[.,]?\\d*)\\s*(mmHg)"),
    ("pH \\(GASOMETRIA VENOSA\\)",
     r"GASOMETRIA\s+VENOSA.*?pH.*?[:|\\s]\\s*([+-]?\\d+[.,]?\\d*)"),
    ("HCO3 \\(GASOMETRIA VENOSA\\)",
     r"GASOMETRIA\s+VENOSA.*?HCO3.*?[:|\\s]\\s*([+-]?\\d+[.,]?\\d*)\\s*(mmol/L)"),
    ("O2 SATURAÇÃO \\(GASOMETRIA VENOSA\\)",
     r"GASOMETRIA\s+VENOSA.*?O2\s+SATURAÇÃO.*?[:|\\s]\\s*([+-]?\\d+[.,]?\\d*)\\s*(%)"),
    ("B\\.E\\. \\(GASOMETRIA VENOSA\\)",
     r"GASOMETRIA\s+VENOSA.*?B\\.E\\..*?[:|\\s]\\s*([+-]?\\d+[.,]?\\d*)\\s*(mmol/L)"),
    ("PSA TOTAL",
     r"PSA\\s+TOTAL.*?RESULTADO\\s*:\\s*([<>]?\\s*\\d+[.,]?\\d*)\\s*(ng/mL)"),
    ("PSA LIVRE",
     r"PSA\\s+LIVRE.*?RESULTADO\\s*:\\s*([<>]?\\s*\\d+[.,]?\\d*)\\s*(ng/mL)"),
    ("RELAÇÃO PSA LIVRE/PSA TOTAL",
     r"RELAÇÃO\\s+PSA\\s+LIVRE/PSA\\s+TOTAL.*?RESULTADO\\s*:\\s*([<>]?\\s*\\d+[.,]?\\d*)\\s*(%)"),
    ("SOMATOMEDINA - IGF-1",
     r"SOMATOMEDINA.*?RESULTADO\\s*:\\s*([<>]?\\s*\\d+[.,]?\\d*)\\s*(ng/mL)"),
    ("TESTOSTERONA LIVRE",
     r"TESTOSTERONA\\s+LIVRE.*?RESULTADO\\s*:\\s*([<>]?\\s*\\d+[.,]?\\d*)\\s*(pg/mL)"),
    ("TESTOSTERONA TOTAL",
     r"TESTOSTERONA\\s+TOTAL.*?RESULTADO\\s*:\\s*([<>]?\\s*\\d+[.,]?\\d*)\\s*(ng/dL)"),
    ("TRANSFERRINA",
     r"TRANSFERRINA.*?RESULTADO\\s*:\\s*([<>]?\\s*\\d+[.,]?\\d*)\\s*(mg/dL)"),
    ("TSH - TIREOESTIMULANTE",
     r"TSH.*?RESULTADO\\s*:\\s*([<>]?\\s*\\d+[.,]?\\d*)\\s*(µ?UI/mL)"),
    ("UREIA URINÁRIA",
     r"UREIA\\s+URIN[AÁ]RIA.*?RESULTADO\\s*:\\s*([<>]?\\s*\\d+[.,]?\\d*)\\s*(mg/24h)"),
    ("VITAMINA B12",
     r"VITAMINA\\s+B12.*?RESULTADO\\s*:\\s*([<>]?\\s*\\d+[.,]?\\d*)\\s*(pg/mL)"),
    ("ZINCO SÉRICO", r"(?:ZINCO SERICO|ZINCO SÉRICO).*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(ug/dL)")



]
       





