TEST_PATTERNS = [
        #("HEMACIAS", r"HEMACIAS\s+(\d+[.,]\d+)\s+(milhões\/mm3)"),
        ("HEMÁCIAS", r"(?:HEMACIAS|HEMÁCIAS)\s+(\d+[.,]\d+)\s+(milhões\/mm3)"),
        ("HEMOGLOBINA", r"HEMOGLOBINA\s+(\d+[.,]\d+)\s+(g\/dL)"),
        #("HEMATOCRITO", r"HEMATOCRITO\s+(\d+[.,]\d+)\s+(\%)"),
        ("HEMATÓCRITO", r"(?:HEMATOCRITO|HEMATÓCRITO)\s+(\d+[.,]\d+)\s+(\%)"),
        ("VCM", r"VCM\s+(\d+[.,]\d+)\s+(fl)"),
        ("HCM", r"HCM\s+(\d+[.,]\d+)\s+(pg)"),
        ("CHCM", r"CHCM\s+(\d+[.,]?\d*)\s*(g/dL)"),
        ("CHCM", r"CHCM\s+(\d+[.,]\d+)\s+(g\/dl)"),
        ("RDW", r"RDW\s+(\d+[.,]\d+)\s+(\%)"),
        #("LEUCOCITOS", r"LEUCOCITOS\s+(\d+[.,]?\d*)"),
        ("LEUCÓCITOS", r"(?:LEUCOCITOS|LEUCÓCITOS)\s+(\d+[.,]?\d*)"),
        ("NEUTROFILOS", r"NEUTROFILOS\s+\d+[.,]?\d*\s+(\d+[.,]?\d*)"),
        ("NEUTRÓFILOS", r"NEUTRÓFILOS\s+\d+[.,]?\d*\s+(\d+[.,]?\d*)"),
        ("PROMIELOCITOS", r"PROMIELOCITOS\s+\d+[.,]?\d*\s+(\d+[.,]?\d*)"),
        ("PROMIELÓCITOS", r"PROMIELÓCITOS\s+\d+[.,]?\d*\s+(\d+[.,]?\d*)"),
        ("MIELÓCITOS", r"MIELÓCITOS\s+\d+[.,]?\d*\s+(\d+[.,]?\d*)"),
        ("MIELOCITOS", r"MIELOCITOS\s+\d+[.,]?\d*\s+(\d+[.,]?\d*)"),
        ("METAMIELÓCITOS", r"METAMIELÓCITOS\s+\d+[.,]?\d*\s+(\d+[.,]?\d*)"),
        ("METAMIELOCITOS", r"METAMIELOCITOS\s+\d+[.,]?\d*\s+(\d+[.,]?\d*)"),
        ("BASTONETES", r"BASTONETES\s+\d+[.,]?\d*\s+(\d+[.,]?\d*)"),
        ("SEGMENTADOS", r"SEGMENTADOS\s+\d+[.,]?\d*\s+(\d+[.,]?\d*)"),
        ("EOSINOFILOS", r"EOSINOFILOS\s+\d+[.,]?\d*\s+(\d+[.,]?\d*)"),
        ("EOSINÓFILOS", r"EOSINÓFILOS\s+\d+[.,]?\d*\s+(\d+[.,]?\d*)"),
        ("BASOFILOS", r"BASOFILOS\s+\d+[.,]?\d*\s+(\d+[.,]?\d*)"),
        ("BASÓFILOS", r"BASÓFILOS\s+\d+[.,]?\d*\s+(\d+[.,]?\d*)"),
        ("PLAQUETAS", r"PLAQUETAS\s+(\d+[.,]?\d*)"),
        ("VPM (Volume Plaquetário Médio)", r"VPM \(Volume Plaquetário Médio\)\s+(\d+[.,]\d*)"),
        ("LINFÓCITOS TÍPICOS", r"LINFÓCITOS TÍPICOS\s+\d+[.,]?\d*\s+(\d+[.,]?\d*)"),
        ("LINFOCITOS TIPICOS", r"LINFOCITOS TIPICOS\s+\d+[.,]?\d*\s+(\d+[.,]?\d*)"),
        ("LINFÓCITOS ATÍPICOS", r"LINFÓCITOS ATÍPICOS\s+\d+[.,]?\d*\s+(\d+[.,]?\d*)"),
        ("LINFOCITOS ATIPICOS", r"LINFOCITOS ATIPICOS\s+\d+[.,]?\d*\s+(\d+[.,]?\d*)"),
        ("LINFOCITOS", r"LINFOCITOS\s+\d+[.,]?\d*\s+(\d+[.,]?\d*)"),
        ("LINFÓCITOS", r"LINFÓCITOS\s+\d+[.,]?\d*\s+(\d+[.,]?\d*)"),
        #("MONOCITOS", r"MONOCITOS\s+\d+[.,]?\d*\s+(\d+[.,]?\d*)"),
        ("MONÓCITOS", r"(?:MONOCITOS|MONÓCITOS)\s+\d+[.,]?\d*\s+(\d+[.,]?\d*)"),
        ("BLASTOS", r"BLASTOS\s+\d+[.,]?\d*\s+(\d+[.,]?\d*)"),
        ("PLAQUETAS", r"PLAQUETAS\s+(\d+)\s+x\s+(10³\/mm3)"),
        ("VMP", r"VMP\s+(\d+[.,]\d+)\s+(fl)"),
        ("GLICOSE", r"GLICOSE.*?RESULTADO\s*:\s*(\d+)\s*(mg\/dL)"),
        ("FERRITINA", r"FERRITINA.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(nanog/mL)"),
        ("HEMOGLOBINA GLICADA - HbA1c", r"HEMOGLOBINA GLICADA - HbA1c.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(%)"),
        ("GLICEMIA MÉDIA ESTIMADA", r"GLICEMIA MÉDIA ESTIMADA\s*:\s*(\d+[.,]?\d*)\s*(mg/dL)"),
        ("GLICEMIA MEDIA ESTIMADA", r"GLICEMIA MEDIA ESTIMADA\s*:\s*(\d+[.,]?\d*)\s*(mg/dL)"),
        ("FERRO SÉRICO", r"FERRO SÉRICO.*?RESULTADO\s*:\s*(\d+[.,]\d*)\s*(mcg\/dL)"),
        ("FERRO SERICO", r"FERRO SERICO.*?RESULTADO\s*:\s*(\d+[.,]\d*)\s*(mcg\/dL)"),
        ("TSH", r"TSH.*?RESULTADO\s*:\s*(\d+[.,]\d+)\s*(µUI\/mL)"),
        ("LH", r"LH.*?RESULTADO\s*:\s*(\d+[.,]\d+)\s*(mUI\/mL)"),
        ("FSH", r"FSH.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(mUI\/mL)"),
        ("1,25-DIHIDROXIVITAMINA D", r"1,25-DIHIDROXIVITAMINA D.*?RESULTADO\s*:\s*(\d+[.,]\d+)\s*(pg\/mL)"),
        ("CREATININA", r"CREATININA.*?RESULTADO\s*[:\-]?\s*(\d+[.,]\d+)\s*(mg\/dL)"),
        ("COLESTEROL TOTAL", r"COLESTEROL TOTAL\s*:\s*(\d+)\s*(mg\/dL)"),
        ("TRIGLICERÍDEOS", r"TRIGLICERÍDEOS\s*:\s*(\d+)\s*(mg\/dL)"),
        ("COLESTEROL HDL", r"COLESTEROL HDL\s*:\s*(\d+)\s*(mg\/dL)"),
        ("COLESTEROL LDL", r"COLESTEROL LDL\s*:\s*(\d+)\s*(mg\/dL)"),
        ("COLESTEROL NÃO HDL", r"COLESTEROL NÃO HDL\s*:\s*(\d+)\s*(mg\/dL)"),
        ("UREIA", r"UREIA.*?RESULTADO\s*:\s*(\d+)\s*(mg\/dL)"),
        ("SÓDIO", r"SÓDIO.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(mmol/L)"),
        ("POTÁSSIO", r"POTÁSSIO.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(mmol/L)"),
        ("POTASSIO", r"POTASSIO.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(mmol/L)"),
        ("FÓSFORO", r"FÓSFORO.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(mg/dL)"),
        ("FOSFORO", r"FOSFORO.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(mg/dL)"),
        ("CÁLCIO", r"CÁLCIO.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(mg/dL)"),
        ("CALCIO", r"CALCIO.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(mg/dL)"),
        ("TRANSAMINASE OXALACÉTICA TGO", r"TRANSAMINASE OXALACÉTICA TGO \(AST\).*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(U/L)"),
        ("TRANSAMINASE PIRÚVICA TGP", r"TRANSAMINASE PIRÚVICA TGP \(ALT\).*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(U/L)"),
        ("FOSFATASE ALCALINA", r"FOSFATASE ALCALINA.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(U/L)"),
        ("GAMA GLUTAMIL TRANSFERASE", r"GAMA GLUTAMIL TRANSFERASE.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(U/L)"),
        ("BILIRRUBINA TOTAL", r"BILIRRUBINA TOTAL.*?:\s*(\d+[.,]?\d*)\s*(mg/dL)"),
        ("BILIRRUBINA DIRETA", r"BILIRRUBINA DIRETA.*?:\s*(\d+[.,]?\d*)\s*(mg/dL)"),
        ("BILIRRUBINA INDIRETA", r"BILIRRUBINA INDIRETA.*?:\s*(\d+[.,]?\d*)\s*(mg/dL)"),
        ("ALBUMINA", r"ALBUMINA\s*\(g/dL\)\s*:\s*(\d+[.,]?\d*)"),
        ("ALFA 1", r"ALFA 1\s*\(g/dL\).*?:\s*(\d+[.,]?\d*)"),
        ("ALFA 2", r"ALFA 2\s*\(g/dL\).*?:\s*(\d+[.,]?\d*)"),
        ("BETA 1", r"BETA 1\s*\(g/dL\).*?:\s*(\d+[.,]?\d*)"),
        ("BETA 2", r"BETA 2\s*\(g/dL\).*?:\s*(\d+[.,]?\d*)"),
        ("GAMA", r"GAMA\s*\(g/dL\).*?:\s*(\d+[.,]?\d*)"),
        ("RELAÇÃO A/G", r"RELAÇÃO A/G.*?:\s*(\d+[.,]?\d*)"),
        ("PROTEÍNAS TOTAIS", r"PROTEÍNAS TOTAIS.*?:\s*(\d+[.,]?\d*)\s*(g/dL)"),
        ("T4 LIVRE", r"T4 LIVRE.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(ng/dL)"),
        ("VITAMINA D3 25-HIDROXI", r"VITAMINA D3 25-HIDROXI.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(ng/mL)"),
        ("DENSIDADE", r"DENSIDADE\s+(\d+[.,]?\d*)"),
        ("PROTEÍNA ROTINA DE URINA", r"PROTEÍNA\s+(Positivo|Negativo)"),
        ("PH ROTINA DE URINA", r"PH\s+(\d+[.,]?\d*)"),
        ("GLICOSE ROTINA DE URINA", r"GLICOSE\s+(Positivo|Negativo)"),
        ("CORPOS CETÔNICOS ROTINA DE URINA", r"CORPOS CETÔNICOS\s+(Positivo|Negativo)"),
        ("NITRITOS ROTINA DE URINA", r"NITRITOS\s+(Positivo|Negativo)"),
        ("HEMOGLOBINA ROTINA DE URINA", r"HEMOGLOBINA\s+(Positivo|Negativo)"),
        ("BILIRRUBINAS ROTINA DE URINA", r"BILIRRUBINAS\s+(Positivo|Negativo)"),
        ("UROBILINOGÊNIO ROTINA DE URINA", r"UROBILINOGÊNIO\s+(Normal|Anormal|Ausente|Presente|Traços)"),
        ("LEUCÓCITOS (URINA)", r"Análise dos Elementos Urinários.*?LEUCÓCITOS\s+(\d+[.,]?\d*)"),
        ("LEUCÓCITOS (URINA)", r"ANALISES DOS ELEMENTOS URINARIOS.*?LEUCÓCITOS\s+(\d+[.,]?\d*)"),
        ("HEMÁCIAS (URINA)", r"Análise dos Elementos Urinários.*?HEMÁCIAS\s+(\d+[.,]?\d*)"),
        ("HEMÁCIAS (URINA)", r"ANALISES DOS ELEMENTOS URINARIOS.*?HEMÁCIAS\s+(\d+[.,]?\d*)"),
        ("CILINDROS (URINA)", r"Análise dos Elementos Urinários.*?CILINDROS\s+(Ausentes|Presentes)"),
        ("CILINDROS (URINA)", r"ANALISES DOS ELEMENTOS URINARIOS.*?CILINDROS\s+(Ausentes|Presentes)"),
        ("CRISTAIS (URINA)", r"Análise dos Elementos Urinários.*?CRISTAIS\s+(Ausentes|Presentes)"),
        ("CRISTAIS (URINA)", r"ANALISES DOS ELEMENTOS URINARIOS.*?CRISTAIS\s+(Ausentes|Presentes)"),
        ("BACTÉRIAS (URINA)", r"Análise dos Elementos Urinários.*?BACTÉRIAS\s+(\w+)"),
        ("BACTÉRIAS (URINA)", r"ANALISES DOS ELEMENTOS URINARIOS.*?BACTÉRIAS\s+(\w+)"),
        ("CÉLULAS EPITELIAIS (URINA)", r"Análise dos Elementos Urinários.*?CÉLULAS EPITELIAIS\s+(Presente|Ausente|Raras)(?:\s*\(\+\))?"),
        ("CÉLULAS EPITELIAIS (URINA)", r"ANALISES DOS ELEMENTOS URINARIOS.*?CÉLULAS EPITELIAIS\s+(Presente|Ausente|Raras)(?:\s*\(\+\))?"),
        ("OUTROS ELEMENTOS (URINA)", r"OUTROS ELEMENTOS(.*?)(?=Observa|Obs|Nota)"),
        ("PARATORMÔNIO", r"PARATORMÔNIO.*?RESULTADO\s*:? \s*(\d+[.,]?\d*)\s*(pg/mL)"),
        ("PSA LIVRE", r"PSA LIVRE\s*:\s*(\d+[.,]?\d*)\s*(ng/mL)"),
        ("PSA TOTAL", r"PSA TOTAL\s*:\s*(\d+[.,]?\d*)\s*(ng/mL)"),
        ("RELAÇÃO PSA LIVRE/PSA TOTAL", r"RELAÇÃO PSA LIVRE/PSA TOTAL\s*:\s*(\d+[.,]?\d*)\s*(%)"),
        ("MAGNÉSIO", r"MAGNÉSIO.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(mg/dL)"),
        ("MAGNESIO", r"MAGNESIO.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(mg/dL)"),
        ("pH (GASOMETRIA VENOSA)", r"GASOMETRIA VENOSA.*?pH.*?:\s*([+-]?\d+[.,]?\d*)"),
        ("PCO2 (GASOMETRIA VENOSA)", r"GASOMETRIA VENOSA.*?PCO2.*?:\s*([+-]?\d+[.,]?\d*)\s*(mmHg)"),
        ("PO2 (GASOMETRIA VENOSA)", r"GASOMETRIA VENOSA.*?PO2.*?:\s*([+-]?\d+[.,]?\d*)\s*(mmHg)"),
        ("HCO3 (GASOMETRIA VENOSA)", r"GASOMETRIA VENOSA.*?HCO3.*?:\s*([+-]?\d+[.,]?\d*)\s*(mmol/L)"),
        ("O2 SATURAÇÃO (GASOMETRIA VENOSA)", r"GASOMETRIA VENOSA.*?O2 SATURAÇÃO.*?:\s*([+-]?\d+[.,]?\d*)\s*(%)"),
        ("B.E. (GASOMETRIA VENOSA)", r"GASOMETRIA VENOSA.*?B\.E\..*?:\s*([+-]?\d+[.,]?\d*)\s*(mmol/L)"),
        ("ANTICORPOS ANTI-TRANSGLUTAMINASE TECIDUAL - IgA", r"ANTICORPOS ANTI-TRANSGLUTAMINASE TECIDUAL - IgA.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(U/mL)"),
        ("SOMATOMEDINA - IGF-1", r"SOMATOMEDINA - IGF-1.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(ng/mL)"),
        ("CARIÓTIPO NÚMERO DE CÉLULAS ANALISADAS", r"NÚMERO DE CÉLULAS ANALISADAS\s*:\s*(\d+)"),
        ("CARIÓTIPO RESOLUÇÃO", r"RESOLUÇÃO\s*:\s*(\d+)\s*BANDAS"),
        ("CARIÓTIPO RESOLUÇÃO", r"RESOLUÇÃO\s*:\s*(\d+)\s*"),
        ("CARIÓTIPO RESULTADO", r"CARIÓTIPO\s*:\s*([0-9]{2},[XY]{2})"),
        ("IMUNOGLOBULINAS IgA", r"IMUNOGLOBULINAS IgA.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(mg/dL)"),
        ("VHS 1ª HORA", r"VHS 1ª HORA.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(mm/1h)"),
        ("PROTROMBINA (PACIENTE)", r"PROTROMBINA \(PACIENTE\).*?:\s*(\d+[.,]?\d*)\s*(segundos)"),
        ("ATIVIDADE DE PROTROMBINA", r"ATIVIDADE DE PROTROMBINA\s*:\s*(\d+[.,]?\d*)\s*(%)"),
        ("PROTROMBINA (RELAÇÃO PACIENTE/PADRÃO)", r"PROTROMBINA \(RELAÇÃO PACIENTE/PADRÃO\)\s*:\s*(\d+[.,]?\d*)"),
        ("RELAÇÃO PACIENTE/CONTROLE", r"RELAÇÃO PACIENTE/CONTROLE\s*:\s*(\d+[.,]?\d*)"),
        ("SISTEMA ABO", r"SISTEMA ABO.*?:\s*([A|B|AB|O]{1,2})"),
        ("FATOR RH", r"FATOR RH.*?:\s*(POSITIVO|NEGATIVO)"),
        ("HCG - GONADOTROFINA CORIONICA", r"HCG - GONADOTROFINA CORIONICA.*?RESULTADO\s*:\s*([<>\=]?\s*\d+[.,]?\d*)\s*(mUI/mL)"),
        ("CARIÓTIPO RESULTADO", r"CARIÓTIPO\s*:\s*([0-9]{2},[^\s]+)"),
        ("HOMA IR", r"HOMA IR\s*(\d+[.,]?\d*)"),
        ("HOMA BETA", r"HOMA BETA\s*(\d+[.,]?\d*)"),
        ("ÁCIDO ÚRICO", r"ÁCIDO ÚRICO.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(mg/dL)"),
        ("CEA/ANTIGENO CARCINOEMBRIOGENICO", r"CEA/ANTIGENO CARCINOEMBRIOGENICO.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(ng/mL)"),
        ("VITAMINA B12", r"VITAMINA B12.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(pg/mL)"),
        ("ÁCIDO FÓLICO", r"ÁCIDO FÓLICO.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(ng/mL)"),
        ("INSULINA BASAL", r"INSULINA BASAL.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(mU/mL)"),
        ("HOMOCISTEÍNA", r"HOMOCISTEÍNA.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(µmol/L)"),
        ("CAXUMBA IgG", r"CAXUMBA IgG.*?RESULTADO\s*:\s*([<>\=]?\s*\d+[.,]?\d*)\s*(UA/mL)"),
        ("TESTOSTERONA TOTAL", r"TESTOSTERONA TOTAL.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(ng/dL)"),
        ("ZINCO SERICO", r"ZINCO SERICO.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(ug/dL)"),
        ("ZINCO SÉRICO", r"ZINCO SÉRICO.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(ug/dL)"),
        ("CÁDMIO", r"CÁDMIO.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(mcg/L)"),
        ("CADMIO", r"CADMIO.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(mcg/L)"),
        ("ALUMÍNIO", r"ALUMÍNIO.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(mcg/L)"),
        ("MERCÚRIO", r"Mercúrio.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(mcg/dL)"),
        ("MERCURIO", r"Mercurio.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(mcg/dL)"),
        ("MANGANÊS", r"MANGANÊS.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(µg/L)"),
        ("MANGANES", r"MANGANES.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(µg/L)"),
        ("ARSÊNICO", r"ARSÊNICO.*?RESULTADO\s*:\s*(INFERIOR A\s*\d+[.,]?\d*)\s*(mcg/L)"),
        ("ARSENICO", r"ARSENICO.*?RESULTADO\s*:\s*(INFERIOR A\s*\d+[.,]?\d*)\s*(mcg/L)"),
        ("CROMO", r"CROMO.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(µg/L)"),
        ("COBALTO", r"COBALTO.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(µg/L)"),
        ("NÍQUEL", r"NÍQUEL.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(mcg/L)"),
        ("N-TELOPEPTÍDEO NTX RESULTADO", r"N-TELOPEPTÍDEO.*?RESULTADO.*?:\s*(\d+[.,]?\d*)\s*(nmol ECO/mM creatinina)"),
        ("N-TELOPEPTÍDEO NTX CONCENTRAÇÃO", r"CONCENTRAÇÃO\s*:\s*(\d+[.,]?\d*)\s*(nmol ECO/L)"),
        ("SOROTIPO 4", r"SOROTIPO\s*4\s*:\s*(Inferior a\s*\d+[.,]?\d*|\d+[.,]?\d*)\s*(microgramas/mL)"),
        ("SOROTIPO 6B", r"SOROTIPO\s*6B\s*:\s*(Inferior a\s*\d+[.,]?\d*|\d+[.,]?\d*)\s*(microgramas/mL)"),
        ("SOROTIPO 9V", r"SOROTIPO\s*9V\s*:\s*(Inferior a\s*\d+[.,]?\d*|\d+[.,]?\d*)\s*(microgramas/mL)"),
        ("SOROTIPO 14", r"SOROTIPO\s*14\s*:\s*(Inferior a\s*\d+[.,]?\d*|\d+[.,]?\d*)\s*(microgramas/mL)"),
        ("SOROTIPO 18C", r"SOROTIPO\s*18C\s*:\s*(Inferior a\s*\d+[.,]?\d*|\d+[.,]?\d*)\s*(microgramas/mL)"),
        ("SOROTIPO 19F", r"SOROTIPO\s*19F\s*:\s*(Inferior a\s*\d+[.,]?\d*|\d+[.,]?\d*)\s*(microgramas/mL)"),
        ("SOROTIPO 23F", r"SOROTIPO\s*23F\s*:\s*(Inferior a\s*\d+[.,]?\d*|\d+[.,]?\d*)\s*(microgramas/mL)",),
        ("IgE MÚLTIPLO PARA PÓ DE CASA", r"IgE MÚLTIPLO PARA PÓ DE CASA \(HX2\).*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(kU/L)"),
        ("IgE MÚLTIPLO PARA EPITÉLIOS E PROTEÍNAS ANIMAIS", r"IgE MÚLTIPLO PARA EPITÉLIOS E PROTEÍNAS ANIMAIS \(EX2\).*?RESULTADO\s*:\s*([<>\=]?\s*\d+[.,]?\d*)\s*(kU/L)"),
        ("IgE MÚLTIPLO PARA ALIMENTOS", r"IgE MÚLTIPLO PARA ALIMENTOS \(FX5\).*?RESULTADO\s*:\s*([<>\=]?\s*\d+[.,]?\d*)\s*(kU/L)"),
        ("IMUNOGLOBULINAS IgE TOTAL", r"IMUNOGLOBULINAS IgE TOTAL.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(UI/mL)"),
        ("CA 125", r"CA 125.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(U/mL)"),
        ("ESTRADIOL", r"ESTRADIOL.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(pg/mL)"),
        ("CPK - CREATINA FOSFOQUINASE", r"CPK - CREATINA FOSFOQUINASE.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(U/L)"),
        ("TESTOSTERONA LIVRE", r"TESTOSTERONA LIVRE.*?RESULTADO\s*:\s*(\d+[.,]?\d*)\s*(pg/mL)"),


]
       





