import re

# Each entry is a tuple: (test_name, (regex_pattern, group_map))
# group_map: {"value_group": int, "unit_group": int/None, "implicit_unit": str/None}
# Use re.DOTALL for patterns that might span multiple lines (like "Método: ... RESULTADO:")
# Use re.IGNORECASE for case-insensitive matching

TEST_PATTERNS = [
    # General Tests (often standalone or in simple blocks)
    ("GLICOSE", (r"GLICOSE\s*Método\s*:.*?RESULTADO:\s*([\d,\.]+)\s*(mg/dL)", {"value_group": 1, "unit_group": 2})),
    ("UREIA", (r"UREIA\s*Método\s*:.*?RESULTADO:\s*([\d,\.]+)\s*(mg/dL)", {"value_group": 1, "unit_group": 2})),
    ("CREATININA", (r"CREATININA\s*Método\s*:.*?RESULTADO\s*([\d,\.]+)\s*(mg/dL)", {"value_group": 1, "unit_group": 2})),
    ("TSH", (r"TSH - TIREOESTIMULANTE\s*Método\s*:.*?RESULTADO:\s*([\d,\.]+)\s*(µUI/mL|uUI/mL)", {"value_group": 1, "unit_group": 2})),
    ("LH - HORMONIO LUTEINIZANTE", (r"LH - HORMONIO LUTEINIZANTE\s*Método\s*:.*?RESULTADO:\s*([\d,\.]+)\s*(mUI/mL)", {"value_group": 1, "unit_group": 2})),
    ("FSH - HORMÔNIO FOLÍCULO ESTIMULANTE", (r"FSH - HORMÔNIO FOLÍCULO ESTIMULANTE\s*Método\s*:.*?RESULTADO:\s*([\d,\.]+)\s*(mUI/mL)", {"value_group": 1, "unit_group": 2})),
    ("COLESTEROL TOTAL", (r"COLESTEROL TOTAL:\s*([\d,\.]+)\s*(mg/dL)", {"value_group": 1, "unit_group": 2})),
    ("TRIGLICERÍDEOS", (r"TRIGLICERÍDEOS:\s*([\d,\.]+)\s*(mg/dL)", {"value_group": 1, "unit_group": 2})),
    ("COLESTEROL HDL", (r"COLESTEROL HDL:\s*([\d,\.]+)\s*(mg/dL)", {"value_group": 1, "unit_group": 2})),
    ("COLESTEROL LDL", (r"COLESTEROL LDL:\s*([\d,\.]+)\s*(mg/dL)", {"value_group": 1, "unit_group": 2})),
    ("COLESTEROL NÃO HDL", (r"COLESTEROL NÃO HDL:\s*([\d,\.]+)\s*(mg/dL)", {"value_group": 1, "unit_group": 2})),
    ("VITAMINA D3 25-HIDROXI", (r"VITAMINA D3 25-HIDROXI.*?RESULTADO:\s*([\d,\.]+)\s*(ng/mL)", {"value_group": 1, "unit_group": 2})),
    ("1,25-DIHIDROXIVITAMINA D", (r"1,25-DIHIDROXIVITAMINA D\s*Método\s*:.*?RESULTADO:\s*([\d,\.]+)\s*(pg/mL)", {"value_group": 1, "unit_group": 2})),
    ("HEMOGLOBINA GLICADA - HbA1c", (r"HEMOGLOBINA GLICADA - HbA1c.*?RESULTADO:\s*([\d,\.]+)\s*(%)", {"value_group": 1, "unit_group": 2})),
    ("VITAMINA B12", (r"VITAMINA B12.*?RESULTADO:\s*([\d,\.]+)\s*(pg/mL)", {"value_group": 1, "unit_group": 2})),
    ("ÁCIDO FÓLICO", (r"ÁCIDO FÓLICO\s*Método\s*:.*?RESULTADO:\s*([\d,\.]+)\s*(ng/mL)", {"value_group": 1, "unit_group": 2})),
    ("COBALTO", (r"COBALTO\s*Método\s*:.*?RESULTADO:\s*([\d,\.]+)\s*(µg/L)", {"value_group": 1, "unit_group": 2})),
    ("NÍQUEL", (r"NÍQUEL\s*Método\s*:.*?RESULTADO:\s*([\d,\.]+)\s*(mcg/L)", {"value_group": 1, "unit_group": 2})),
    ("CÁDMIO", (r"CÁDMIO\s*Método\s*:.*?RESULTADO:\s*([\d,\.]+)\s*(mcg/L)", {"value_group": 1, "unit_group": 2})),
    ("ALUMÍNIO", (r"ALUMÍNIO\s*Método\s*:.*?RESULTADO:\s*([\d,\.]+)\s*(mcg/L)", {"value_group": 1, "unit_group": 2})),
    ("MERCÚRIO", (r"MERCÚRIO\s*Método\s*:.*?RESULTADO:\s*([\d,\.]+)\s*(mcg/dL)", {"value_group": 1, "unit_group": 2})),
    ("MANGANÊS", (r"MANGANÊS\s*Método\s*:.*?RESULTADO:\s*([\d,\.]+)\s*(µg/L)", {"value_group": 1, "unit_group": 2})),
    ("ARSÊNICO", (r"ARSÊNICO\s*Método\s*:.*?RESULTADO:\s*(INFERIOR A [\d,\.]+|[\d,\.]+)\s*(mcg/L)", {"value_group": 1, "unit_group": 2})),
    ("CROMO", (r"CROMO\s*Método\s*:.*?RESULTADO:\s*([\d,\.]+)\s*(µg/L)", {"value_group": 1, "unit_group": 2})),
    ("SOMATOMEDINA - IGF-1", (r"SOMATOMEDINA - IGF-1\s*Método\s*:.*?RESULTADO:\s*([\d,\.]+)\s*(ng/mL)", {"value_group": 1, "unit_group": 2})),
    ("ANTICORPOS ANTI-TRANSGLUTAMINASE TECIDUAL - IgA", (r"ANTICORPOS ANTI-TRANSGLUTAMINASE TECIDUAL - IgA.*?RESULTADO:\s*([\d,\.]+)\s*(U/mL)", {"value_group": 1, "unit_group": 2})),
    ("VHS 1ª HORA", (r"VHS 1ª HORA\s*Método\s*:.*?RESULTADO:\s*([\d,\.]+)\s*(mm/1h)", {"value_group": 1, "unit_group": 2})),
    ("IMUNOGLOBULINAS IgA", (r"IMUNOGLOBULINAS IgA\s*Método\s*:.*?RESULTADO:\s*([\d,\.]+)\s*(mg/dL)", {"value_group": 1, "unit_group": 2})),
    ("HCG - GONADOTROFINA CORIONICA", (r"HCG - GONADOTROFINA CORIONICA\s*Método\s*:.*?RESULTADO:\s*(<[\d,\.]+|[\d,\.]+)\s*(mUI/mL)", {"value_group": 1, "unit_group": 2})),
    ("MAGNÉSIO", (r"MAGNÉSIO\s*Método\s*:.*?RESULTADO:\s*([\d,\.]+)\s*(mg/dL)", {"value_group": 1, "unit_group": 2})),
    ("FÓSFORO", (r"FÓSFORO\s*Método\s*:.*?RESULTADO:\s*([\d,\.]+)\s*(mg/dL)", {"value_group": 1, "unit_group": 2})),
    ("CÁLCIO", (r"CÁLCIO\s*Método\s*:.*?RESULTADO:\s*([\d,\.]+)\s*(mg/dL)", {"value_group": 1, "unit_group": 2})),
    ("TRANSAMINASE OXALACÉTICA TGO (AST)", (r"TRANSAMINASE OXALACÉTICA TGO \(AST\)\s*Método\s*:.*?RESULTADO:\s*([\d,\.]+)\s*(U/L)", {"value_group": 1, "unit_group": 2})),
    ("TRANSAMINASE PIRÚVICA TGP (ALT)", (r"TRANSAMINASE PIRÚVICA TGP \(ALT\)\s*Método\s*:.*?RESULTADO:\s*([\d,\.]+)\s*(U/L)", {"value_group": 1, "unit_group": 2})),
    ("FOSFATASE ALCALINA", (r"FOSFATASE ALCALINA\s*Método\s*:.*?RESULTADO:\s*([\d,\.]+)\s*(U/L)", {"value_group": 1, "unit_group": 2})),
    ("GAMA GLUTAMIL TRANSFERASE", (r"GAMA GLUTAMIL TRANSFERASE\s*Método\s*:.*?RESULTADO:\s*([\d,\.]+)\s*(U/L)", {"value_group": 1, "unit_group": 2})),
    ("BILIRRUBINA TOTAL...", (r"BILIRRUBINA TOTAL...\s*:\s*([\d,\.]+)\s*(mg/dL)", {"value_group": 1, "unit_group": 2})),
    ("BILIRRUBINA DIRETA..", (r"BILIRRUBINA DIRETA..\s*:\s*([\d,\.]+)\s*(mg/dL)", {"value_group": 1, "unit_group": 2})),
    ("BILIRRUBINA INDIRETA", (r"BILIRRUBINA INDIRETA:\s*([\d,\.]+)\s*(mg/dL)", {"value_group": 1, "unit_group": 2})),
    ("CULTURA DE URINA", (r"CULTURA DE URINA\s*Método\s*:.*?Resultado:\s*(NEGATIVA)", {"value_group": 1, "unit_group": None})),
    ("SANGUE OCULTO - PESQUISA", (r"SANGUE OCULTO - PESQUISA\s*Método\s*:.*?RESULTADO:\s*(NEGATIVA)", {"value_group": 1, "unit_group": None})),
    ("CARIÓTIPO EM SANGUE PERIFÉRICO", (r"CARIÓTIPO\s*:\s*([0-9]{2},[XY]{2})", {"value_group": 1, "unit_group": None})),
    ("CARIÓTIPO EM SANGUE PERIFÉRICO", (r"CARIÓTIPO\s*:\s*([0-9]{2},[^\s]+)", {"value_group": 1, "unit_group": None})),

  # ("CARIÓTIPO COM BANDA G PARA 50 CÉLULAS", (r"CARIÓTIPO COM BANDA G PARA 50 CÉLULAS.*?CARIÓTIPO:\s*([\w,\(\)\+\s]+)", {"value_group": 1, "unit_group": None})),
    ("CEA/ANTIGENO CARCINOEMBRIOGENICO", (r"CEA/ANTIGENO CARCINOEMBRIOGENICO\s*Método\s*:.*?RESULTADO:\s*([\d,\.]+)\s*(ng/mL)", {"value_group": 1, "unit_group": 2})),
    ("PSA LIVRE", (r"PSA LIVRE:\s*([\d,\.]+)\s*(ng/mL)", {"value_group": 1, "unit_group": 2})),
    ("PSA TOTAL", (r"PSA TOTAL:\s*([\d,\.]+)\s*(ng/mL)", {"value_group": 1, "unit_group": 2})),
    ("RELAÇÃO PSA LIVRE/PSA TOTAL", (r"RELAÇÃO PSA LIVRE/PSA TOTAL:\s*([\d,\.]+)\s*(%)", {"value_group": 1, "unit_group": 2})),
    ("PARATORMÔNIO", (r"PARATORMÔNIO\s*Método.*?RESULTADO\s*([\d,\.]+)\s*(pg/mL)", {"value_group": 1, "unit_group": 2})),
    ("HOMOCISTEÍNA", (r"HOMOCISTEÍNA\s*Método.*?RESULTADO:\s*([\d,\.]+)\s*(µmol/L)", {"value_group": 1, "unit_group": 2})),
    ("ZINCO SERICO", (r"ZINCO SERICO\s*Método.*?RESULTADO:\s*([\d,\.]+)\s*(ug/dL)", {"value_group": 1, "unit_group": 2})),
    ("CAXUMBA IgG", (r"CAXUMBA IgG\s*Método.*?RESULTADO:\s*([<>\d,\.]+)\s*(UA/mL)", {"value_group": 1, "unit_group": 2})),
    ("TESTOSTERONA TOTAL", (r"TESTOSTERONA TOTAL\s*Método.*?RESULTADO:\s*([\d,\.]+)\s*(ng/dL)", {"value_group": 1, "unit_group": 2})),
    ("ANDROSTANEDIOL GLUCURONIDE [3 ALFA DIOL]", (r"ANDROSTANEDIOL GLUCURONIDE \[3 ALFA DIOL\].*?RESULTADO:\s*([\d,\.]+)\s*(ng/mL)", {"value_group": 1, "unit_group": 2})),
    ("SÓDIO", (r"SÓDIO\s*Método.*?RESULTADO:\s*([\d,\.]+)\s*(mmol/L)", {"value_group": 1, "unit_group": 2})),
    ("POTÁSSIO", (r"POTÁSSIO\s*Método.*?RESULTADO:\s*([\d,\.]+)\s*(mmol/L)", {"value_group": 1, "unit_group": 2})),
    ("INSULINA BASAL", (r"INSULINA BASAL\s*Método.*?RESULTADO:\s*([\d,\.]+)\s*(mU/mL)", {"value_group": 1, "unit_group": 2})),
    ("HOMA IR", (r"HOMA IR\s*([\d,\.]+)", {"value_group": 1, "unit_group": None})),
    ("HOMA BETA", (r"HOMA BETA\s*([\d,\.]+)", {"value_group": 1, "unit_group": None})),
    ("FERRO SÉRICO", (r"FERRO SÉRICO\s*Método\s*:.*?RESULTADO:\s*([\d,\.]+)\s*(mcg/dL)", {"value_group": 1, "unit_group": 2})),
    ("FERRITINA", (r"FERRITINA\s*Método\s*:.*?RESULTADO:\s*([\d,\.]+)\s*(nanog/mL)", {"value_group": 1, "unit_group": 2})),
    ("T4 LIVRE", (r"T4 LIVRE\s*Método\s*:.*?RESULTADO:\s*([\d,\.]+)\s*(ng/dL)", {"value_group": 1, "unit_group": 2})),
    ("ÁCIDO ÚRICO", (r"ÁCIDO ÚRICO\s*Método\s*:.*?RESULTADO:\s*([\d,\.]+)\s*(mg/dL)", {"value_group": 1, "unit_group": 2})),
    ("N-TELOPEPTÍDEO (CROSS-LINKS) - NTX", (r"N-TELOPEPTÍDEO \(CROSS-LINKS\) - NTX\s*Método\s*:.*?RESULTADO...\s*:\s*([\d,\.]+)\s*(nmol ECO/mM creatinina)", {"value_group": 1, "unit_group": 2})),
    ("N-TELOPEPTÍDEO CONCENTRAÇÃO", (r"CONCENTRAÇÃO:\s*([\d,\.]+)\s*(nmol ECO/L)", {"value_group": 1, "unit_group": 2})),
    
    # Estimativa da Taxa de Filtração Glomerular (eTFG)
    ("eTFG (ESTIMATIVA DA TAXA DE FILTRAÇÃO GLOMERULAR)", (r"(?:ESTIMATIVA DA TAXA DE FILTRAÇÃO GLOMERULAR|eTFG).*?RESULTADO(?: ADULTO NEGRO| ADULTO NÃO NEGRO)?(?:\.{5})?:\s*([><*,\d\.]+)\s*(mL/min/1\.73m2)", {"value_group": 1, "unit_group": 2})),

    # Coagulogram Tests
    ("PROTROMBINA (PADRÃO)", (r"PROTROMBINA \(PADRÃO\)\.{4}:\s*([\d,\.]+)\s*(segundos)", {"value_group": 1, "unit_group": 2})),
    ("PROTROMBINA (PACIENTE)", (r"PROTROMBINA \(PACIENTE\)\.{2}:\s*([\d,\.]+)\s*(segundos)", {"value_group": 1, "unit_group": 2})),
    ("ATIVIDADE DE PROTROMBINA", (r"ATIVIDADE DE PROTROMBINA:\s*([\d,\.]+)\s*(%)", {"value_group": 1, "unit_group": 2})),
    ("PROTROMBINA (RELAÇÃO PACIENTE/PADRÃO)", (r"PROTROMBINA \(RELAÇÃO PACIENTE/PADRÃO\):\s*([\d,\.]+)", {"value_group": 1, "unit_group": None})),
    ("RELAÇÃO PADRÃO INTERNACIONAL (INR)", (r"RELAÇÃO PADRÃO INTERNACIONAL \(INR\)\.{3}:\s*([\d,\.]+)", {"value_group": 1, "unit_group": None})),
    ("SENSIBILIDADE INTERNACIONAL (ISI)", (r"SENSIBILIDADE INTERNACIONAL \(ISI\)\.{4}:\s*([\d,\.]+)", {"value_group": 1, "unit_group": None})),
    ("PLASMA CONTROLE", (r"PLASMA CONTROLE\.{10}:\s*([\d,\.]+)\s*(segundos)", {"value_group": 1, "unit_group": 2})),
    ("PLASMA PACIENTE", (r"PLASMA PACIENTE\.{10}:\s*([\d,\.]+)\s*(segundos)", {"value_group": 1, "unit_group": 2})),
    ("RELAÇÃO PACIENTE/CONTROLE", (r"RELAÇÃO PACIENTE/CONTROLE:\s*([\d,\.]+)", {"value_group": 1, "unit_group": None})),

    # Blood Group (Qualitative)
    ("SISTEMA ABO", (r"SISTEMA ABO\.{3}:\s*(A|B|AB|O)", {"value_group": 1, "unit_group": None})),
    ("FATOR RH", (r"FATOR RH\.{6}:\s*(POSITIVO|NEGATIVO)", {"value_group": 1, "unit_group": None})),

    # Hemograma Tests
    ("HEMACIAS (Hemograma)", (r"HEM[ÁA]CIAS\s*([\d,\.]+)\s*(milhões/mm3)", {"value_group": 1, "unit_group": 2})),
    ("HEMOGLOBINA (Hemograma)", (r"HEMOGLOBINA\s*([\d,\.]+)\s*(g/dL)", {"value_group": 1, "unit_group": 2})),
    ("HEMATOCRITO (Hemograma)", (r"HEMAT[ÓO]CRITO\s*([\d,\.]+)\s*(%)", {"value_group": 1, "unit_group": 2})),
    ("VCM (Hemograma)", (r"VCM\s*([\d,\.]+)\s*(fl)", {"value_group": 1, "unit_group": 2})),
    ("HCM (Hemograma)", (r"HCM\s*([\d,\.]+)\s*(pg)", {"value_group": 1, "unit_group": 2})),
    ("CHCM (Hemograma)", (r"CHCM\s*([\d,\.]+)\s*(g/d[L|l])", {"value_group": 1, "unit_group": 2})),
    ("RDW (Hemograma)", (r"RDW\s*([\d,\.]+)\s*(%)", {"value_group": 1, "unit_group": 2})),
    ("PLAQUETAS (Hemograma)", (r"PLAQUETAS\s*([\d,\.]+)\s*(x 10³/mm3|mil/mm3)", {"value_group": 1, "unit_group": 2})),
    ("VMP (Volume Plaquetário Médio)", (r"V[PM][\s\(]*(?:Volume Plaquetário Médio)?[\)]?\s*([\d,\.]+)\s*(fl)", {"value_group": 1, "unit_group": 2})),

    # Leucograma Tests
    ("LEUCOCITOS (Leucograma)", (r"(?:LEUCOCITOS|LEUCÓCITOS)\s+(\d+[.,]?\d*)", {"value_group": 1, "unit_group": None, "implicit_unit": "/mm3"})),
    ("BASTONETES (Leucograma)", (r"BASTONETES\s*\d+\s*([\d,\.]+)", {"value_group": 1, "unit_group": None, "implicit_unit": "/mm3"})),
    ("SEGMENTADOS (Leucograma)", (r"SEGMENTADOS\s*\d+\s*([\d,\.]+)", {"value_group": 1, "unit_group": None, "implicit_unit": "/mm3"})),
    ("EOSINOFILOS (Leucograma)", (r"EOSIN[ÓO]FILOS\s*\d+\s*([\d,\.]+)", {"value_group": 1, "unit_group": None, "implicit_unit": "/mm3"})),
    ("BASOFILOS (Leucograma)", (r"BAS[ÓO]FILOS\s*\d+\s*([\d,\.]+)", {"value_group": 1, "unit_group": None, "implicit_unit": "/mm3"})),
    ("LINFOCITOS (Leucograma)", (r"LINFOCITOS\s*\d+\s*([\d,\.]+)", {"value_group": 1, "unit_group": None, "implicit_unit": "/mm3"})), # Note: Specific to file 1's aggregate.
    ("MONOCITOS (Leucograma)", (r"MON[ÓO]CITOS\s*\d+\s*([\d,\.]+)", {"value_group": 1, "unit_group": None, "implicit_unit": "/mm3"})),
    ("NEUTRÓFILOS (Leucograma)", (r"NEUTRÓFILOS\s*\d+\s*([\d,\.]+)", {"value_group": 1, "unit_group": None, "implicit_unit": "/mm3"})),
    ("PROMIELÓCITOS (Leucograma)", (r"PROMIELÓCITOS\s*\d+\s*([\d,\.]+)", {"value_group": 1, "unit_group": None, "implicit_unit": "/mm3"})),
    ("MIELÓCITOS (Leucograma)", (r"MIELÓCITOS\s*\d+\s*([\d,\.]+)", {"value_group": 1, "unit_group": None, "implicit_unit": "/mm3"})),
    ("METAMIELÓCITOS (Leucograma)", (r"METAMIELÓCITOS\s*\d+\s*([\d,\.]+)", {"value_group": 1, "unit_group": None, "implicit_unit": "/mm3"})),
    ("LINFÓCITOS TÍPICOS (Leucograma)", (r"LINFÓCITOS TÍPICOS\s*\d+\s*([\d,\.]+)", {"value_group": 1, "unit_group": None, "implicit_unit": "/mm3"})),
    ("LINFÓCITOS ATÍPICOS (Leucograma)", (r"LINFÓCITOS ATÍPICOS\s*\d+\s*([\d,\.]+)", {"value_group": 1, "unit_group": None, "implicit_unit": "/mm3"})),
    ("BLASTOS (Leucograma)", (r"BLASTOS\s*\d+\s*([\d,\.]+)", {"value_group": 1, "unit_group": None, "implicit_unit": "/mm3"})),

    # Gasometria Venosa
    ("pH (Gasometria)", (r"pH\.{15}:\s*([\d,\.]+)", {"value_group": 1, "unit_group": None})),
    ("PCO2", (r"PCO2\.{13}:\s*([\d,\.]+)\s*(mmHg)", {"value_group": 1, "unit_group": 2})),
    ("PO2", (r"PO2\.{14}:\s*([\d,\.]+)\s*(mmHg)", {"value_group": 1, "unit_group": 2})),
    ("HCO3", (r"HCO3\.{13}:\s*([\d,\.]+)\s*(mmol/L)", {"value_group": 1, "unit_group": 2})),
    ("O2 SATURAÇÃO", (r"O2 SATURAÇÃO\.{5}:\s*([\d,\.]+)\s*(%)", {"value_group": 1, "unit_group": 2})),
    ("B.E", (r"B\.E\.{14}:\s*([-\d,\.]+)\s*(mmol/L)", {"value_group": 1, "unit_group": 2})),

    # Urinalysis (EAS / Rotina de Urina)
    #("PH ROTINA DE URINA", r"PH\s+(\d+[.,]?\d*)"),
    ("DENSIDADE (Urina)", (r"DENSIDADE\s*([\d,\.]+)", {"value_group": 1, "unit_group": None})),
    ("PH (Urina)", (r"PH\s+(\d+[.,]?\d*)", {"value_group": 1, "unit_group": None})),
    ("PROTEÍNAS (Urina)", (r"PROTEÍNA[S]?\s*(Negativo|Positivo \+[\+]?|Ausente|Presente \(\+\))", {"value_group": 1, "unit_group": None})),
    ("GLICOSE (Urina)", (r"GLICOSE\s*(Negativo|Positivo \+[\+]?)", {"value_group": 1, "unit_group": None})),
    ("CORPOS CETÔNICOS (Urina)", (r"CORPOS CETÔNICOS\s*(Negativo|Positivo \+[\+]?)", {"value_group": 1, "unit_group": None})),
    ("BILIRRUBINAS (Urina)", (r"BILIRRUBINAS\s*(Negativo|Positivo \+[\+]?)", {"value_group": 1, "unit_group": None})),
    ("HEMOGLOBINA (Urina)", (r"HEMOGLOBINA\s*(Negativo|Positivo \+[\+]?)", {"value_group": 1, "unit_group": None})),
    ("NITRITOS (Urina)", (r"NITRITOS\s*(Negativo|Positivo \+[\+]?)", {"value_group": 1, "unit_group": None})),
    ("UROBILINOGÊNIO (Urina)", (r"UROBILINOGÊNIO\s*(Negativo|Normal)", {"value_group": 1, "unit_group": None})),

    ("LEUCÓCITOS (Urina)", (r"(?:ANALISES DOS ELEMENTOS URINARIOS|Análise dos Elementos Urinários).*?LEUCÓCITOS\s+(\d+[.,]?\d*)", {"value_group": 1, "unit_group": 2})),
    ("HEMÁCIAS (Urina)", (r"(?:ANALISES DOS ELEMENTOS URINARIOS|Análise dos Elementos Urinários).*?HEMÁCIAS\s+(\d+[.,]?\d*)", {"value_group": 1, "unit_group": 2})),
    ("CILINDROS (Urina)", (r"CILINDROS\s*(Ausentes|Presente \(\+\))", {"value_group": 1, "unit_group": None})),
    ("BACTÉRIAS (Urina)", (r"BACTÉRIAS\s*(Escassa|Presente \(\+\)|Não Vizualizada)", {"value_group": 1, "unit_group": None})),
    ("CÉLULAS EPITELIAIS (Urina)", (r"CÉLULAS EPITELIAIS\s*(Raras|Ausentes|Presente \(\+\))", {"value_group": 1, "unit_group": None})),
    ("CRISTAIS (Urina)", (r"CRISTAIS[ :]?\s*(Ausentes|Presente \(\+\))", {"value_group": 1, "unit_group": None})),

    # Eletroforese de Proteínas
    ("ALBUMINA (g/dL)", (r"ALBUMINA \(g/dL\):\s*([\d,\.]+)\s*g/dL", {"value_group": 1, "unit_group": 2})),
    ("ALBUMINA (%)", (r"ALBUMINA \(\%\)\.{3}:\s*([\d,\.]+)\s*%", {"value_group": 1, "unit_group": 2})),
    ("ALFA 1 (g/dL)", (r"ALFA 1 \(g/dL\)\.{2}:\s*([\d,\.]+)\s*g/dL", {"value_group": 1, "unit_group": 2})),
    ("ALFA 1 (%)", (r"ALFA 1 \(\%\)\.{5}:\s*([\d,\.]+)\s*%", {"value_group": 1, "unit_group": 2})),
    ("ALFA 2 (g/dL)", (r"ALFA 2 \(g/dL\)\.{2}:\s*([\d,\.]+)\s*g/dL", {"value_group": 1, "unit_group": 2})),
    ("ALFA 2 (%)", (r"ALFA 2 \(\%\)\.{5}:\s*([\d,\.]+)\s*%", {"value_group": 1, "unit_group": 2})),
    ("BETA 1 (g/dL)", (r"BETA 1 \(g/dL\)\.{2}:\s*([\d,\.]+)\s*g/dL", {"value_group": 1, "unit_group": 2})),
    ("BETA 1 (%)", (r"BETA 1 \(\%\)\.{5}:\s*([\d,\.]+)\s*%", {"value_group": 1, "unit_group": 2})),
    ("BETA 2 (g/dL)", (r"BETA 2 \(g/dL\)\.{2}:\s*([\d,\.]+)\s*g/dL", {"value_group": 1, "unit_group": 2})),
    ("BETA 2 (%)", (r"BETA 2 \(\%\)\.{5}:\s*([\d,\.]+)\s*%", {"value_group": 1, "unit_group": 2})),
    ("GAMA (g/dL)", (r"GAMA \(g/dL\)\.{4}:\s*([\d,\.]+)\s*g/dL", {"value_group": 1, "unit_group": 2})),
    ("GAMA (%)", (r"GAMA \(\%\)\.{7}:\s*([\d,\.]+)\s*%", {"value_group": 1, "unit_group": 2})),
    ("RELAÇÃO A/G", (r"RELAÇÃO A/G\.{4}:\s*([\d,\.]+)", {"value_group": 1, "unit_group": None})),
    ("PROTEÍNAS TOTAIS", (r"PROTEÍNAS TOTAIS\.{5}:\s*([\d,\.]+)\s*(g/dL)", {"value_group": 1, "unit_group": 2})),
]